apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-aqdf
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0003-tenant/tkrw-pr712-0075-0003-app/devfile-sample-aqdf@sha256:b0e6062ee0faa9a1ebd2270593330c0e06b4b3c870f07036e8901d999ad2a0f2
        name: my-nodejs
        resources: {}
status: {}
